baseURL: "https://stopcovid19-ichikawa.netlify.app/"
copyright: "&copy; 2020 Meiryo7743"
defaultContentLanguage: ja
defaultContentLanguageInSubdir: true
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: UA-177104755-1
hasCJKLanguage: true

disableKinds:
  - RSS
  - section
  - taxonomyTerm

languages:
  ja:
    languageCode: ja
    languageName: 日本語
    title: 【非公式】市川市新型コロナウイルス感染症対策サイト
    weight: 10
    params:
      description: 当サイトは，市川市内における新型コロナウイルス感染症（COVID-19）及びそれに関連する情報を提供いたします。当サイトは個人が制作した非公式サイトです。
      image: "/img/ogp_ja.png"
      notice:
        emergency: false
        translation: false
  # ja-hrkt:
  #   languageCode: ja
  #   languageName: やさしいにほんご
  #   title: 【ひこうしき】 いちかわし 新型コロナウイルス かんせんしょう じょうほう サイト
  #   weight: 11
  #   params:
  #     description: 当サイトは，市川市内における新型コロナウイルス感染症（COVID-19）及びそれに関連する情報を提供いたします。当サイトは個人が制作した非公式サイトです。
  #     image: "/img/ogp_ja.png"
  #     notice:
  #       emergency: false
  #       translation: true
  en:
    languageCode: en
    languageName: English
    title: "[UNOFFICIAL] Ichikawa COVID-19 Information Website"
    weight: 20
    params:
      description: This site provides the latest information on COVID-19 in Ichikawa. Note that it is unofficial website developed by individual.
      image: "/img/ogp_en.png"
      notice:
        emergency: false
        translation: true

markup:
  goldmark:
    renderer:
      unsafe: false

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepEndTags: false

privacy:
  disqus:
    disable: true
  googleAnalytics:
  # disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
