baseURL = "https://stopcovid19-ichikawa.netlify.app"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
disableKinds = ["RSS", "section", "taxonomyTerm", "term"]
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true
googleAnalytics = "G-6SX4L2MEKS"
hasCJKLanguage = true

[author]
name = "Meiryo7743"

[languages.en]
languageCode = "en"
languageName = "English"
title = "[UNOFFICIAL] Ichikawa COVID-19 Information Site"
weight = 20

[languages.en.params]
dateFormat = "Jan 2"
description = "This site provides the latest information on COVID-19 in Ichikawa. Note that it is unofficial website developed by individual."
ogp = "/img/en-ogp-2021-01-04.png"

[languages.en.params.notice]
emergency = true
translate = true

[languages.ja]
languageCode = "ja"
languageName = "日本語"
title = "【非公式】市川市新型コロナウイルス感染症情報サイト"
weight = 10

[languages.ja.params]
dateFormat = "1月2日"
description = "当サイトは，市川市内における新型コロナウイルス感染症（COVID-19）及びそれに関連する情報を提供いたします。当サイトは個人が制作した非公式サイトです。"
ogp = "/img/ja-ogp-2021-01-04.png"

[languages.ja.params.notice]
emergency = true
translate = false

[markup.goldmark.renderer]
unsafe = false

[minify]
minifyOutput = true

[minify.tdewolff.html]
keepEndTags = false

[outputs]
home = ["HTML"]
page = ["HTML"]

[params]
copyrightYear = 2020

[[params.favicon]]
href = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAC0AgMAAABAo+6hAAAADFBMVEX////I6/yO1vhgxvZmg+dfAAACsElEQVR42u2XMY7bMBBFR9qFBcSF+xiBbxAfwaySIkUOkEM4TWrpCD5CbrBtmiz3COrSqnDq3UIBZDjmj0caG9EuRA7TBeBv2DzI5JvRmKKUlJSUlJSUf4yJgYsmhi4d6TMDaj2dASfSZw1UUVvpYo4JREicA3vSx8IRfVehrwwtgabATrXrppe4Racy4nqJKusM1pQDqooydyDaAppuWQFAxUsbhjMLMGgBZzSF+WWB9wDQaIpe8WZUTgqgY9vAYQXUGn297ToHDkF9p6FlXS+xCunjoy3BYAG0AX2OV7bYSZtnPn1tf1SOGdr8taetYQaLnxjsf+rep09eSwb7Y/xwk68BsGOLvLBtFm8n6YU9yTi5uFw7TNNH0ddchsrs0UOLvstiKIOHxnU6SGmWIboUi33ZbYCWqZb3S4HSS8vElF4su7WftjhcLc7wdeOnj6jFItumAI37v/SdgvQTWxR9nYa+6nuiMkiLxTlrQZgWfVxUG6Rz0Qe0in3PB33gNrdh2rK+4dUsw/SxHUatU9Eww6i1OrrX9/PdRkuXQH27IZWTfv480BfSPXsBmZhWSxti6epnC61/9kZHy59OqaW7/pBauqFzELVvG0PniDFYRNGLqH2Xepoog5ZmKneIqGW220TsOzP6rqopp5WabinTd2yvcKWnKy9dPaMfzvTdJP1tTHPPvllM0vbjmK6Jbu+m6ccXO6EP0zRe0ls1bbiv1LR/nsxHtFxpJj83sjH9m6S5JrJ61ie09n0m5SO6IYL3brod9/fMf++djd+d8J36Srcy6jW03B0bLV3RDZzR0ua8tqSk3VuzQBWi10LD7lcdhVIIDcDuKJjPQis/vK90E0M7iqH3UbSJoTvS5UYqr0x5pg+kzfxM16TPwlEMvY+iTQx9SykpKSkpKf9Z/gB8RomwmPtydwAAAABJRU5ErkJggg=="
rel = "apple-touch-icon"
sizes = "180x180"

[[params.favicon]]
href = "/img/logo.svg"
rel = "icon"
type = "image/svg+xml"

[[params.favicon]]
href = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEABAMAAACuXLVVAAAAD1BMVEX////d8/665/uS2PlgxfWeYt+oAAAEOklEQVR42u2bW27jMAxFJbkLUMZegIt4AU7CBdQW97+mGcCN7yRyVWQgkSiG5y99gMcSr8W0jjMMwzAMwzAMwzAMwzAMwzAMwzAMw/jJeKeLp9WpQsyLU2TiP1ycBqjPPDslPPHG6JTw/El0SgTeSGoG3d3AadHzxuo0QBL0bgcwuDgtnsIYxE08DLZXYgZhPQgj3U1ErnzJDCbBWyPtnYcwTruJVPfPMAAiAgM6DzqC9XsUywwkWiBkl+tJuD5AGDcuIgHMDSbBDiB+5IL6Amczaq2eP5kfc7gK1ce+85kfWCQCmOI+EQFq3ogoGXcdMO7tMTcOIMI+MJjbj+o+v8IJYXgwjE3rXw6+lk0HTQMABuxANqpL1O8ZjG1HdQTwqSlBPB7VT3UDmGJeH986GNX7pXYA8wYkLE42KHdcRcCj1QBCgfZ4NgjMS/0AZisNl6cwnqiOQIe+ykMBw9yAuI7AW/oigFj1wzAS1xLghB47DkU4NKgnwHQcwAilLIypqgDTeBCKsXBS3biuwFL+AxlCgUWqK7Ae1CqcFJ6bCaB+4aTw1EwAASyFgriVQPlUjFgkvrYRwMjzzai4OmohgGstBLDffoBbCLxRHkA6CGB6d40EmHCtxwEM9xm9kUB6CuDAqI8Nie0EOPHyxXs11E+umUDpBoANWZoKpFIAkZEgIOA5CyD64a2xQD6IYUM+sBntBPIS2JA14vbQSKB8AvMo0ISlE5ijgEDIA7hzkWjCLj0GcGKAjmwpwLe/6/cMkpAAE/OMAIIrerKtABNOYIDRob3Amte/pQE/KiWA9wmn2H3cBTo5AWJ0fx8H8S2YHvee+ANerQVwAqMUnaPsFvDOduUevyQvALobywrks/L/KDA6QAoCKTrACgIXpywQHehkBfJCb7IC+Q4MsgLYA/yGcgwn1r0ReQYqZ8HAyitArNsDgVk1BZ6VBNABygKkJLC6T5jSTUEAlabgnOoKnLUnoquOAHK44DSSFMC9eFYT4He3oSbAo7bAXF8gviKAE7mrJjDEVwRWCKShkkCKLwikXSC5rpIAp38RCLOjWgK8viKwM9yqCTC90AMg1BPgF1IAeg2BMXtvIiwQ3Z1fJCuAHqz9DImnFwQW1K/3nG94QWBG/YpPWoeywFELUI36oCsLgIQA1H3Ati8K5C1AqF+JqSSQ7XfX4CHrqSCQLwDqV8PTdwLogAEBrIi/FgSQwYbPFvuyABag2dPVRQEUDHgpKoAOQABFBRABvBIUwCjSIYDCArPHDiSnIHDackiNP2njvxS4MadxexVdQ8KBALgGBLAVfUFA5rPgfVng4ppzLgksToDiOyMhymO5kgBuAGoCgvXL/y9QEpidKCH/v6EoGNURQGkIAgr1MaojgOL4TUCnPkZ1BFAJ1FcCAVQC9ZVYnWEYhmEYhmEYhmEYhmEYhmEYhmH8cH4D77QGqtjcD9MAAAAASUVORK5CYII="
rel = "icon alternate"
sizes = "256x256"
type = "image/png"

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = false

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = true
