baseURL: "https://stopcovid19-ichikawa.netlify.app"
defaultContentLanguage: ja
defaultContentLanguageInSubdir: true
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: true
hasCJKLanguage: true

# Params
params:
  author: Meiryo7743

# Languages
languages:
  ja:
    languagename: "日本語"
    title: "【非公式】市川市新型コロナウイルス感染症対策サイト"
    weight: 10
    params:
      description: "当サイトは，市川市内における新型コロナウイルス感染症（COVID-19）に関する最新情報を提供いたします。なお，当サイトは非公式です。"

  en:
    languageName: "English"
    title: "【UNOFFICIAL】Ichikawa COVID-19 Information Website"
    weight: 20
    params:
      description: "The website that provides the latest infomation on COVID-19 in Ichikawa. Note that this is unofficial."

# Markup
markup:
  goldmark:
    renderer:
      unsafe: false

# Minification
minify:
  minifyOutput: true
  tdewolff:
    html:
      keepEndTags: false

# Do not generate
disableKinds:
  - RSS
  - section
  - taxonomyTerm

# Privacy
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
