baseURL = "https://stopcovid19-ichikawa.netlify.app"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
disableKinds = ["RSS", "section", "taxonomyTerm", "term"]
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true
googleAnalytics = "G-6SX4L2MEKS"
hasCJKLanguage = true

[author]
name = "Meiryo7743"

[languages.en]
languageCode = "en"
languageName = "English"
title = "[UNOFFICIAL] Ichikawa COVID-19 Information Site"
weight = 20

[languages.en.params]
description = "This site provides the latest information on COVID-19 in Ichikawa. Note that it is unofficial website developed by individual."
ogp = "/img/en-ogp-20201225.png"

[languages.en.params.notice]
emergency = false
translate = true

[languages.ja]
languageCode = "ja"
languageName = "日本語"
title = "【非公式】市川市新型コロナウイルス感染症情報サイト"
weight = 10

[languages.ja.params]
description = "当サイトは，市川市内における新型コロナウイルス感染症（COVID-19）及びそれに関連する情報を提供いたします。当サイトは個人が制作した非公式サイトです。"
ogp = "/img/ja-ogp-20201225.png"

[languages.ja.params.notice]
emergency = false
translate = false

[markup.goldmark.renderer]
unsafe = false

[minify]
minifyOutput = true

[minify.tdewolff.html]
keepEndTags = false

[outputs]
home = ["HTML"]
page = ["HTML"]

[params]
copyrightYear = 2020

[[params.favicon]]
href = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAC0BAMAAADP4xsBAAAAFVBMVEX////n9/6+5/ub2vmC0fdtyvVexPTa5jqKAAADWElEQVR42u2ZvXKjMBSFr0g2NVns1GQnuDYzWWo7iVVvPFnqDT/3/R9hsQScIU7IWFx1+irbxcf10UHGQIFAIBAIBAKBQCAQCIigYvLFpvHlzphrP+4VdxzJB1fsz51wR7n3FwlvPS1kR5uSDwrusBVUJIsyblPB4ihnfTwJlTZuk81eLGc7bFSaCpoVzUmENTNXqLdgxxO4VtxT0XIw6n6soNR+YgMe4lX2nUi9leaBNjUFRL0lytzeayNMM2axRDZGtEUsHaXIOmbjAsK97+u9dLuDJEGhEzRmWe2qyXFqvMyX1A4LhqrkC3dYuJoYVTG02w9u5Vq7dFKV8SM17t7qxbF26aQqeS/EDhurorm4dggW6zYKscNmfLH6hTtesff17yKcLxF3/OXL1eWhLzQGnFyR2AO+sYu6PdRkUbaEk2x25mXDLmpG7ZAvoRr4NpdPzS1ZbAmteVpozcvUcKE4W8y/QL36pIT7vvht5pa1VSdwoR7D/LvrJVMfuOOJDCi1nf+ZblzVqPd5VRKjXKZm/VXtKlc192rUDjuhTWa3eGqOz2un2R55I6CelrAYVrNcrMbeh/lNUNo5a6hRaFxSxjJZ/57UbvwGhYC60GPtuCcVWsai1aidoTm9vRPIusA+atlwLDU1M+EC4vb+4UZSjdq9E8Vr8/FaTG3N/O807y9zqIVZQ82W3XA1dqvFpkbt8MMgq96S5VpeHZPlhlk46yP13AlPjTxIS6thYn9Za+GsUb4rD1Pv8LfB0ynD3rLOmOWzJvzaCE9d20Usm9KTOsppLa5uY6NO6Vo+66MJpLOLTo32KfH9Gm4/U/POXZ1/o36nE4qfL1fr7by6suqKHNRtOquurTp9dFBzw/OBWGLtoGaeX0ZLUsqqsa3+dGhIMa9u+5mH4C9B6Vl1Zc1ud26jck79pz+p3G72RXNqY1ux60Og5HM1wtXuNz/X5+rzoV/JiYdzNXTRssccX6jjsZ41ialxkitjjuXUqMQP3ESTUWMRCxRaTl2v3lJSKLQ7q4/qVnNzH4k8usumasuBn0iADdTSz+3UmRq1EwBq7KNe1E1KftQotLw6J1FWUO9JmGxQP5E0qrDqI8mjiAiFFgeFFge1EyelQCAQCAQCgUAgEAi48h8f6elo3BJkfgAAAABJRU5ErkJggg=="
rel = "apple-touch-icon"
sizes = "180x180"

[[params.favicon]]
href = "/img/logo.svg"
rel = "icon"
type = "image/svg+xml"

[[params.favicon]]
href = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEABAMAAACuXLVVAAAAD1BMVEX////c8/265vuR1/hfxPTfCQk6AAAEO0lEQVR42u2aYY6jOBCFbdMHcC8cgFFzAEjqAA2u+59ppSWbN7EZSxnZVRpNff/oENWHXQ+bDs4wDMMwDMMwDMMwDMMwDMMwDMMwDONPxjtdPB1OFWLenSILM/PmNEB95tUp4YlPZqeE5wfRKRH4JKkZDHySnBYjnxxOAyRB73YAg81pkYUxiJt4GJxHYgbhuAgjPUxkrnwvDBaMhcjcb1kYl6eJVPevMAAiAhM6DzqC9UcUywwgJbEGwMCTZP3ADLIw8iYSwNJgEewA4lc21BdYm1Hr8Pxgfc3hIVQf885f/MIuEcAUn2kA1L0RUTJChxFA4s5b9ZCHfWKw9t+q+/IKF4ThxTB2rb9d/K3YHXQNAJgwA9lWXab+yGDuu1VHALOmBPF6q/7ZNoAplvXx0cVWfdxbB7BsQMLgFBvlgZsIeLQaQCjQHrlBYN7bB7AYabhkYfykNgID+qoMBQxLA+I2Ah+pDGA26pdhJG4lwAk9dh2KcGFA3E6AKQsg6kOpCGNLAab5IhRzZaW6NxbY6/8gQygwSG0FjotalZXCczcB1K+sFJ66CSCAtVAQ9xKor4oRg8S3PgIIYCUU03/nUw8BXGslgON5AvcQ+KAygHQVwB+ukwATrvU6gOEh6DsJpCyAU1bfU2cBTrz/4lkN9ZPrJlC7AWBC9q4CqfashowEAQHPRQDRDx+dBcqNGCbkG5PRVYBQ4nVCjohPOwnUV2CeBZqwtgJzFBAIZQCfbBJNOCSMdlaf0ZE9Bfj+c/2RQRISYGJeEUBwQ0/2FWDCCgywdegvcJT172nCqVICeE74jMP3/wKDnAAxun+Mk/gULK9zT/wNLwmBKXsCoK8oOwX85Lxyjy/JC4DhzrIC5V75bxSYHSAFgRQdYAWBzSkLRAcGWYGy0IesQDkDk6wA5gDfUI7hwro3Is9AZS2YWHkEiHV7IDCrpsCzkgA6QFmAlAQO94Ap3RUEUGkJzqmOwJf2juimI4Ac7ueJ0gK4F69qAvzDnagJ8KwtsLYXiO8IYEUemglM8R2BAwJpaiSQ4hsC6SmQ3NBIgNPvCITVUSsBPt4RwBfvzQSY3ugBENoJ8BspAKOGwJw9m4gL4OHoH9IQSNn4txDw9IbAjvrt3vMNbwisqN/wTetQF7hqAWpRHwx1AZAQgLYv2I5VgbIFCPUbsdQEivkeOrxkvVQEygFA/WZ4qghkHTAhgA3xt4oAMtjx3WJfF8AAdHu7uiqAggGHggJlB2xOWAARwJGgALYiAwIoLLB6zEByCgKfZw4JN4Au+F8K3JnTfB5F15FwIQBuAQHsxXgtAFbXmbEusLnufNUEdidD/clITyA5IC+AG4CagGD9+u8FSgKrEyWUvxsKs0AAARSFIKBQH1t1BFAcfwro1MdWHQFUAvWVQACVQH0lDmcYhmEYhmEYhmEYhmEYhmEYhmEYfzj/ArFSBqtRmDX0AAAAAElFTkSuQmCC"
rel = "icon alternate"
sizes = "256x256"
type = "image/png"

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = false

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = true
