[[redirects]]
from = "/*"
to = "/en/404.html"
status = 404
force = false
conditions = {Language = ["en"]}

[[redirects]]
from = "/*"
to = "/ja/404.html"
status = 404
force = false

[[redirects]]
from = "/about"
to = "/en/about"
status = 301
force = false
conditions = {Language = ["en"]}

[[redirects]]
from = "/about"
to = "/ja/about"
status = 301
force = false

[[redirects]]
from = "/contacts"
to = "/https:/forms.gle/rJAhPqckU1Ak7tFQ9"
status = 301
force = false

[[redirects]]
from = "/en/cards/detail-of-patients"
to = "/en/cards/details-of-patients-with-symptoms"
status = 301
force = false

[[redirects]]
from = "/en/cards/details-of-all-patients"
to = "/en/cards/details-of-patients-with-symptoms"
status = 301
force = false

[[redirects]]
from = "/en/cards/details-of-all-patients-without-symptoms"
to = "/en/cards/details-of-patients-without-symptoms"
status = 301
force = false

[[redirects]]
from = "/en/cards/details-of-latest-30-patients"
to = "/en/cards/details-of-latest-30-patients-with-symptoms"
status = 301
force = false

[[redirects]]
from = "/en/cards/number-of-patients"
to = "/en/cards/the-number-of-patients"
status = 301
force = false

[[redirects]]
from = "/en/cards/predicted-number-of-toei-subway-passengers"
to = "/en/changes-in-the-number-of-passengers-on-toei-subway"
status = 301
force = false

[[redirects]]
from = "/en/cards/the-number-of-patients"
to = "/en/cards/the-number-of-patients-with-symptoms"
status = 301
force = false

[[redirects]]
from = "/en/contacts"
to = "/https:/forms.gle/rJAhPqckU1Ak7tFQ9"
status = 301
force = false

[[redirects]]
from = "/ja/cards/detail-of-patients"
to = "/ja/cards/details-of-patients-with-symptoms"
status = 301
force = false

[[redirects]]
from = "/ja/cards/details-of-all-patients"
to = "/ja/cards/details-of-patients-with-symptoms"
status = 301
force = false

[[redirects]]
from = "/ja/cards/details-of-all-patients-without-symptoms"
to = "/ja/cards/details-of-patients-without-symptoms"
status = 301
force = false

[[redirects]]
from = "/ja/cards/details-of-latest-30-patients"
to = "/ja/cards/details-of-latest-30-patients-with-symptoms"
status = 301
force = false

[[redirects]]
from = "/ja/cards/number-of-patients"
to = "/ja/cards/the-number-of-patients"
status = 301
force = false

[[redirects]]
from = "/ja/cards/predicted-number-of-toei-subway-passengers"
to = "/ja/changes-in-the-number-of-passengers-on-toei-subway"
status = 301
force = false

[[redirects]]
from = "/ja/cards/the-number-of-patients"
to = "/ja/cards/the-number-of-patients-with-symptoms"
status = 301
force = false
