[[redirects]]
force = false
from = "/en/*"
status = 404
to = "/en/404.html"

[[redirects]]
force = false
from = "/ja/*"
status = 404
to = "/ja/404.html"

[[redirects]]
force = false
from = "/"
status = 404
to = "/ja/404.html"
