[subway]
dst = "./data/"
src = "https://raw.githubusercontent.com/tokyo-metropolitan-gov/covid19/development/data/metro.json"

[[subway.data]]
data_passengers = "changes-in-the-rates-of-toei-subway-passengers.json"
raw = "raw-changes-in-the-rates-of-toei-subway-passengers.json"
