# 旧デザインからのリダイレクト
# about
[[redirects]]
  from = "/about"
  to = "/ja/about"
  force = true

 [[redirects]]
  from = "/en/about"
  to = "/en/about"
  force = true
  conditions = {Language = ["en"]}

# contacts
[[redirects]]
  from = "/contacts"
  to = "https://forms.gle/rJAhPqckU1Ak7tFQ9"
  force = true

 [[redirects]]
  from = "/en/contacts"
  to = "https://forms.gle/rJAhPqckU1Ak7tFQ9"
  force = true

# 404
[[redirects]]
  from = "/*"
  to = "/ja/404.html"
  status = 404
  force = false

 [[redirects]]
  from = "/*"
  to = "/en/404.html"
  status = 404
  force = false
  conditions = {Language = ["en"]}
