[[redirects]]
from = "/ja/contacts"
to = "https://forms.gle/rJAhPqckU1Ak7tFQ9"
force = true

[[redirects]]
from = "/en/contacts"
to = "https://forms.gle/rJAhPqckU1Ak7tFQ9"
force = true

[[redirects]]
from = "/ja/cards/details-of-all-patients"
to = "/ja/cards/details-of-patients-with-symptoms"
force = true

[[redirects]]
from = "/en/cards/details-of-all-patients"
to = "/en/cards/details-of-patients-with-symptoms"
force = true

[[redirects]]
from = "/ja/cards/details-of-latest-30-patients"
to = "/ja/cards/details-of-latest-30-patients-with-symptoms"
force = true

[[redirects]]
from = "/en/cards/details-of-latest-30-patients"
to = "/en/cards/details-of-latest-30-patients-with-symptoms"
force = true

[[redirects]]
from = "/ja/cards/the-number-of-patients"
to = "/ja/cards/the-number-of-patients-with-symptoms"
force = true

[[redirects]]
from = "/en/cards/the-number-of-patients"
to = "/en/cards/the-number-of-patients-with-symptoms"
force = true

[[redirects]]
from = "/ja/cards/changes-in-the-number-of-passengers-on-toei-subway"
to = "/ja/cards/changes-in-the-rates-of-toei-subway-passengers"
force = true

[[redirects]]
from = "/en/cards/changes-in-the-number-of-passengers-on-toei-subway"
to = "/en/cards/changes-in-the-rates-of-toei-subway-passengers"
force = true

[[redirects]]
from = "/ja/*"
to = "/ja/404.html"
force = false
status = "404"

[[redirects]]
from = "/en/*"
to = "/en/404.html"
force = false
status = "404"

