name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 15 31 12 *" # YYYY-01-01 00:00 JST (automatically update copyright year)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          submodules: true # Fetch Hugo themes (true OR recursive)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true
          hugo-version: 0.75.1

      - name: Build
        run: TZ=Asia/Tokyo hugo --minify -e production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: production
